name: 🐛 Bug Report
description: Report unexpected behavior or errors
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting, check if this bug was already reported in [issues](https://github.com/thmasq/github-monitor/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug).
  - type: input
    id: title
    attributes:
      label: Summary
      description: "Ex: 'Crash when clicking button X'"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: "What happened? When does it occur?"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to page X
        2. Click on Y
        3. See error Z
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What should happen?"
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Windows
        - macOS
        - Linux
        - Other (specify below)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Project/System Version
      placeholder: "Ex: v1.2.0"
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      placeholder: "Logs, screenshots, etc."